config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :gals
  resources :guys

  root 'relationships#index'

end

app/models/gal.rb
class Gal < ActiveRecord::Base
  has_many :relationships
  has_many :guys, through: :relationships
end

app/models/guy.rb
class Guy < ActiveRecord::Base
  has_many :relationships
  has_many :gals, through: :relationships
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :guy
  belongs_to :gal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gals_controller.rb
class GalsController < ApplicationController
  before_action :set_gal, only: [:show, :edit, :update, :destroy]

  def index
    @gals = Gal.all
  end

  def show
    @relationships = @gal.relationships
  end

  def new
    @gal = Gal.new
  end

  def edit
  end

  def create
    @gal = Gal.new(gal_params)

    respond_to do |format|
      if @gal.save
        format.html { redirect_to @gal, notice: 'Gal was successfully created.' }
        format.json { render :show, status: :created, location: @gal }
      else
        format.html { render :new }
        format.json { render json: @gal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gal.update(gal_params)
        format.html { redirect_to @gal, notice: 'Gal was successfully updated.' }
        format.json { render :show, status: :ok, location: @gal }
      else
        format.html { render :edit }
        format.json { render json: @gal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gal.destroy
    respond_to do |format|
      format.html { redirect_to gals_url, notice: 'Gal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_gal
    @gal = Gal.find(params[:id])
  end

  def gal_params
    params.require(:gal).permit(:id, :name, :worst_bad_date)
  end
end

app/controllers/guys_controller.rb
class GuysController < ApplicationController
  before_action :set_guy, only: [:show, :edit, :update, :destroy]

  def index
    @guys = Guy.all
  end

  def show
  end

  def new
    @guy = Guy.new
  end

  def edit
  end

  def create
    @guy = Guy.new(guy_params)

    respond_to do |format|
      if @guy.save
        format.html { redirect_to @guy, notice: 'Guy was successfully created.' }
        format.json { render :show, status: :created, location: @guy }
      else
        format.html { render :new }
        format.json { render json: @guy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @guy.update(guy_params)
        format.html { redirect_to @guy, notice: 'Guy was successfully updated.' }
        format.json { render :show, status: :ok, location: @guy }
      else
        format.html { render :edit }
        format.json { render json: @guy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @guy.destroy
    respond_to do |format|
      format.html { redirect_to guys_url, notice: 'Guy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_guy
    @guy = Guy.find(params[:id])
  end

  def guy_params
    params.require(:guy).permit(:id, :name, :number_of_emails_sent)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  def index
    @relationships = Relationship.all
  end

  def show
    @guy = Guy.find(@relationship.guy_id)
    @gal = Gal.find(@relationship.gal_id)
  end

  def new
    @relationship = Relationship.new
  end

  def edit
  end

  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully recorded.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to relationships_url, notice: 'Relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_relationship
    @relationship = Relationship.find(params[:id])
  end

  def relationship_params
    params.require(:relationship).permit(:id, :guy_id, :gal_id, :first_date, :next_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gals_helper.rb
module GalsHelper
end

app/helpers/guys_helper.rb
module GuysHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/gals/_form.html.erb
<%= form_for(@gal) do |f| %>
  <% if @gal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gal.errors.count, "error") %> prohibited this gal from being saved:</h2>

      <ul>
      <% @gal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :worst_bad_date %><br>
    <%= f.text_field :worst_bad_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gals/edit.html.erb
<h1>Editing Gal</h1>

<%= render 'form' %>

<%= link_to 'Show', @gal %> |
<%= link_to 'Back', gals_path %>

app/views/gals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gals.each do |gal| %>
      <tr>
        <td><%= gal.name %></td>
        <td><%= link_to 'Show', gal %></td>
        <td><%= link_to 'Edit', edit_gal_path(gal) %></td>
        <td><%= link_to 'Destroy', gal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gal', new_gal_path %><br />
<%= link_to 'See the Guys', guys_path %><br />
<%= link_to 'Go Back to Relationships', relationships_path %>

app/views/gals/new.html.erb
<h1>New Gal</h1>

<%= render 'form' %>

<%= link_to 'Back', gals_path %>

app/views/gals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gal.name %>
</p>

<p>
  <strong>Worst bad date:</strong>
  <%= @gal.worst_bad_date %>
</p>

<%= link_to 'Edit', edit_gal_path(@gal) %> |
<%= link_to 'Back', gals_path %>

app/views/guys/_form.html.erb
<%= form_for(@guy) do |f| %>
  <% if @guy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guy.errors.count, "error") %> prohibited this guy from being saved:</h2>

      <ul>
      <% @guy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number_of_emails_sent %><br>
    <%= f.number_field :number_of_emails_sent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guys/edit.html.erb
<h1>Editing Guy</h1>

<%= render 'form' %>

<%= link_to 'Show', @guy %> |
<%= link_to 'Back', guys_path %>

app/views/guys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guys.each do |guy| %>
      <tr>
        <td><%= guy.name %></td>
        <td><%= link_to 'Show', guy %></td>
        <td><%= link_to 'Edit', edit_guy_path(guy) %></td>
        <td><%= link_to 'Destroy', guy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guy', new_guy_path %><br />
<%= link_to 'See the Gals', gals_path %><br />
<%= link_to 'Go Back to Relationships', relationships_path %>

app/views/guys/new.html.erb
<h1>New Guy</h1>

<%= render 'form' %>

<%= link_to 'Back', guys_path %>

app/views/guys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guy.name %>
</p>

<p>
  <strong>Number of emails sent:</strong>
  <%= @guy.number_of_emails_sent %>
</p>

<%= link_to 'Edit', edit_guy_path(@guy) %> |
<%= link_to 'Back', guys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineDatingRelationship</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guy %><br>
    <%= f.select(:guy_id, Guy.all.map{|guy| [guy.name, guy.id]}) %>
  </div>
  <div class="field">
    <%= f.label :gal_id %><br>
    <%= f.select(:gal_id, Gal.all.map{|gal| [gal.name, gal.id]}) %>
  </div>
  <div class="field">
    <%= f.label :first_date %><br>
    <%= f.date_select :first_date %>
  </div>
  <div class="field">
    <%= f.label :next_date, "Was there a second date?" %><br>
    <%= f.check_box :next_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Online Dating Relationships</h1>

<table>
  <thead>
    <tr>
      <th>Guy</th>
      <th>Gal</th>
      <th>First date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= relationship.guy.name %></td>
        <td><%= relationship.gal.name %></td>
        <td><%= relationship.first_date %></td>
        <td><%= link_to 'Did they go on a second date? Click here to find out!', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %><br/>
<p>See all <%= link_to 'Guys', guys_path %> or <%= link_to 'Gals', gals_path %></p>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guy:</strong>
  <%= @guy.name %>
</p>

<p>
  <strong>Gal:</strong>
  <%= @gal.name %>
</p>

<p>
  <strong>First date:</strong>
  <%= @relationship.first_date %>
</p>

<p>
  <strong>Did they go on a second date?:</strong>
  <% if @relationship.next_date == true %>
    <em>Yes! They did!</em>
  <% else %>
    <em>No. They didn't, the first date was terrible.</em>
  <% end %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>